name: Build + Test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yaml
  test:
    name: Test
    needs: build
    uses: ./.github/workflows/reusable-test.yaml
    with:
      result-artifact-url: ${{ needs.build.outputs.artifact-url }}
      run-coverage: true
